[toolchain]
anchor_version = "0.31.1"
solana_version = "2.3.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
safe_pump = "JBjKCmvSK3dMPfKk1WGD8nZfw8yAZHtuZ3GLo7NpCHX7"
seed_coin = "generate_new_progrm_id"
[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["safe_pump"]
